kind: Service
apiVersion: v1
metadeta:
  name: train-schedule-service
spec:
  type: NodePort
  selector:
    app: train-schedule
  ports:
  - protocals: TCP
    port: 8080
    nodePort: 8080
 ---
 apiVersion: extensions/v1beta1
 kind: Deployment
 metadata:
   name:train-schedule-deployment
   labels:
     apps: train-schedule
 spec:
   replicas: 2
   selector:
     metadata:
       app: train-schedule
   template:
     metadata:
       labels:
         app: train-schedule
     spec: 
       containers:
       - name: train-schedule
         image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
         ports:
         - containerPort: 8080
         
